version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ../db_files:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: toor
       MYSQL_DATABASE: czspaun 
       #MYSQL_USER: docky
       #MYSQL_PASSWORD: docky
     ports:
      - 3306:3306

   phpapp:
     depends_on:
       - db
     image: php:5.6
     build:
      context: .
      dockerfile: Dockerfile
     links:
      - db
     volumes:
      - ../www:/var/www/html
      - ../www/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ../www/virtualhost.conf:/etc/apache2/sites-available/001-virtualhost.conf
     environment:
       DB_HOST: db:3306
       DB_PASSWORD: toor
     ports:
      - 80:80

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - "8080:80"
     volumes:
      - ../phpmyadmin/sessions:/sessions
